### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by T1xx1** [kisvegabor/abbreviations-in-code#33]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### Description • 🟢 desc

<br>

## Pros
- In the list, there's descriptor.

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
We need to decide if `dsc` or `desc` is better. 

[Here](https://www.allacronyms.com/description/abbreviated) and [here](https://www.abbreviations.com/abbreviation/description) `dsc` is not event mentioned. Actually initially I added it because I use `dsc` in my codes, but it seems I should change it.  :slightly_smiling_face:

**Comment by T1xx1** [comment]
I think desc is better. As usual, one letter will not change a lot and desc is more descriptive.

**Comment by kisvegabor** [comment]
Ok, let's go for "desc" for both "description" and "descriptor". Can you add it?

**Comment by T1xx1** [comment]
> Ok, let's go for "desc" for both "description" and "descriptor". Can you add it?

Sure, doing it this afternoon.

**Comment by T1xx1** [comment]
Added in #50
